name: Hello world

on:
  push:
   branches:
    - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name:
        run: echo "Hello World"